import os
import time
from pathlib import Path
from datetime import datetime

class HistoryLogManager:
    @staticmethod
    def _get_template_header(day_str):
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Qpyt-UI Session Log - {day_str}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg-color: #0f172a;
            --card-bg: #1e293b;
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
            --accent: #6366f1;
            --border: rgba(255, 255, 255, 0.1);
        }}
        body {{
            background-color: var(--bg-color);
            color: var(--text-main);
            font-family: 'Inter', sans-serif;
            margin: 0;
            padding: 2rem;
            line-height: 1.5;
        }}
        .container {{
            max-width: 1000px;
            margin: 0 auto;
        }}
        header {{
            border-bottom: 2px solid var(--accent);
            padding-bottom: 1rem;
            margin-bottom: 2rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        h1 {{ margin: 0; font-weight: 600; font-size: 1.5rem; }}
        .date {{ color: var(--text-muted); font-size: 0.9rem; }}
        
        .entry {{
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 12px;
            margin-bottom: 2rem;
            display: grid;
            grid-template-columns: 350px 1fr;
            overflow: hidden;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
        }}
        .image-side {{
            background: #000;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            overflow: hidden;
        }}
        .image-side img {{
            width: 100%;
            height: 100%;
            object-fit: contain;
            transition: transform 0.3s ease;
        }}
        .image-side:hover img {{
            transform: scale(1.05);
        }}
        .info-side {{
            padding: 1.5rem;
            display: flex;
            flex-direction: column;
            gap: 1rem;
        }}
        .prompt {{
            font-style: italic;
            color: var(--text-main);
            background: rgba(0,0,0,0.2);
            padding: 1rem;
            border-radius: 8px;
            font-size: 0.95rem;
            border-left: 3px solid var(--accent);
        }}
        .metadata-grid {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 0.5rem;
            font-size: 0.85rem;
        }}
        .meta-item b {{ color: var(--accent); }}
        .meta-item {{ color: var(--text-muted); }}
        
        footer {{
            text-align: center;
            margin-top: 4rem;
            color: var(--text-muted);
            font-size: 0.8rem;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Qpyt-UI Session Log</h1>
            <div class="date">{day_str}</div>
        </header>
        <div id="log-entries">
"""

    @staticmethod
    def _get_template_footer():
        return """
        </div>
        <footer>Generated by Qpyt-UI - All rights reserved</footer>
    </div>
</body>
</html>"""

    @classmethod
    def add_to_log(cls, output_dir: Path, image_name: str, metadata: dict, execution_time: float):
        try:
            log_file = output_dir / "index.html"
            output_dir.mkdir(parents=True, exist_ok=True)
            day_str = output_dir.name
            timestamp = datetime.now().strftime("%H:%M:%S")

            # Prepare entry HTML
            m = metadata
            entry_html = f"""
            <!-- ENTRY_START -->
            <div class="entry">
                <div class="image-side" onclick="window.open('{image_name}', '_blank')">
                    <img src="{image_name}" alt="Generated Image">
                </div>
                <div class="info-side">
                    <div style="display: flex; justify-content: space-between; font-size: 0.8rem; color: var(--text-muted);">
                        <span>{timestamp}</span>
                        <span>{execution_time:.1f}s</span>
                    </div>
                    <div class="prompt">"{m.get('prompt', 'No prompt')}"</div>
                    <div class="metadata-grid">
                        <div class="meta-item"><b>Seed:</b> {m.get('seed', 'N/A')}</div>
                        <div class="meta-item"><b>Model:</b> {m.get('model_name', 'N/A')}</div>
                        <div class="meta-item"><b>Steps:</b> {m.get('num_inference_steps', 'N/A')}</div>
                        <div class="meta-item"><b>Guidance:</b> {m.get('guidance_scale', 'N/A')}</div>
                        <div class="meta-item"><b>Resolution:</b> {m.get('width', '?')}x{m.get('height', '?')}</div>
                        <div class="meta-item"><b>Format:</b> {image_name.split('.')[-1].upper()}</div>
                    </div>
                    {f'<div style="font-size: 0.8rem; color: #10b981; margin-top: 0.5rem; background: rgba(16, 185, 129, 0.1); padding: 0.8rem; border-radius: 6px; border: 1px solid rgba(16, 185, 129, 0.2);"><b>Applied LoRAs:</b><br/>' + "<br/>".join([f"• {Path(l['path']).stem} (Weight: {l['weight']})" for l in m['loras'] if l.get('enabled', True)]) + '</div>' if m.get('loras') and any(l.get('enabled', True) for l in m['loras']) else ''}
                </div>
            </div>
            <!-- ENTRY_END -->
"""

            if not log_file.exists():
                # Create new log
                with open(log_file, "w", encoding="utf-8") as f:
                    f.write(cls._get_template_header(day_str))
                    f.write(entry_html)
                    f.write(cls._get_template_footer())
            else:
                # Append incrementally before the footer
                with open(log_file, "r", encoding="utf-8") as f:
                    content = f.read()
                
                # We find the insertion point just before </div>\n        </div>\n        <footer>
                # Or simply before the markers or the footer.
                # A safer way is to find the LAST <!-- ENTRY_END --> and insert after, 
                # or find the <div id="log-entries"> and insert after its start for reverse chronological,
                # but user said "incrémenter", usually means bottom.
                
                insertion_point = content.find('<!-- ENTRY_END -->')
                if insertion_point != -1:
                    # Find the LAST one
                    last_point = content.rfind('<!-- ENTRY_END -->') + len('<!-- ENTRY_END -->')
                    new_content = content[:last_point] + entry_html + content[last_point:]
                else:
                    # Fallback if no entry yet
                    split_marker = '<div id="log-entries">'
                    pos = content.find(split_marker) + len(split_marker)
                    new_content = content[:pos] + entry_html + content[pos:]
                
                with open(log_file, "w", encoding="utf-8") as f:
                    f.write(new_content)

        except Exception as e:
            print(f"Failed to update history log: {e}")
